### ISSUE TITLE
React Example .env file

### ISSUE THREAD

**Issue by turfday** [directus/examples#105]
Successfully executed the NextJS example with Directus.  However, when I run the react example, does not appear to be reading the .env file.

**Comment by br41nslug** [comment]
React requires all environment variables to have a `REACT_APP_` prefix else it will ignore them.

**Comment by turfday** [comment]
Got it.  At least for me, the REACT example does not run correctly out-of-the box even when just copying the .env.example file to .env "as is".  Nothing is retrieved from the local Directus instance.

**Comment by azrikahar** [comment]
@turfday thanks for reporting! Turns out to be an unintended CORS related error due to the previous version upgrade for the Directus example. Fixed in #106 👍
