### ISSUE TITLE
Auth example for OAuth2.0 integration

### ISSUE THREAD

**Issue by harish0sim** [directus/examples#117]
Directus server is integrated with Github OAuth2. Would love to look at example, how to integrated JS(Svelte) Client login?

**Comment by azrikahar** [comment]
The SDK doesn't currently support SSO login. You can upvote this suggestion in https://github.com/directus/directus/discussions/4463 👍 Seems like there's also a custom endpoint shared by a community member here: https://github.com/directus/directus/discussions/4463#discussioncomment-1592315, so perhaps that can be a possible reference.
