### ISSUE TITLE
Directus Examples: Integrations

### ISSUE THREAD

**Issue by AgnesNM** [directus/examples#135]
Hello, just noticed that Blitz on Directus' examples, under the integrations section has been discontinued. 

![Screenshot from 2022-08-01 18-32-49](https://user-images.githubusercontent.com/47296541/182185936-99f3a237-8ee0-4b53-bf23-fe2c5a9c3a64.png)

**Comment by rijkvanzanten** [comment]
Blitz was discontinued? Do you have a source? Their GitHub / website still looks active at first glance

**Comment by AgnesNM** [comment]
@rijkvanzanten oops, that's Blitz the static generator...[Blitz](https://github.com/TimboKZ/blitz) my bad...

**Comment by rijkvanzanten** [comment]
Wrong blitz!
