### ISSUE TITLE
CORS Issue with React Example and Directus Cloud

### ISSUE THREAD

**Issue by turfday** [directus/examples#139]
I tried to migrate the React Directus example instance from a local port 8055 instance to the Directus Cloud.  The react client code example remains on my local machine.  (Note:  it would be nice if I could have exported the articles data model from the local instance and into the Directus cloud, but that did not appear possible, so I retyped the "articles" data model into the Directus cloud from scratch).

Anyway, because the frontend and backend of the example program are now on two different domains, there is a CORS issue.  Specifically, the error in the browser developer console is that  "... from origin http://localhost:3000 has been blocked by CORS policy: Response to preflight request doesn't pass access control check.  Redirect is not allow for a preflight request."

Note that the cloud API works fine when the URL is entered directly into the browser; the CORS issue arises with the REACT example program running locally on port 3000 connecting to the Directus cloud..

I changed the .env file to the following but that did not help:
REACT_APP_DIRECTUS_URL="http://wfqfwpau.directus.app"
CORS_ENABLED"='true'
CORS_ORIGIN='*'

Any hints on how to get the REACT example to work with the Directus Cloud?

Thanks

**Comment by rijkvanzanten** [comment]
I think the problem here is that you're using `http://` instead of `https://` to the Directus Cloud instance. That in turn causes the browser to throw the error, as the redirect from http->https isn't allowed in the preflight. Try setting your env var to:

```
REACT_APP_DIRECTUS_URL="https://wfqfwpau.directus.app/"
```

**Comment by turfday** [comment]
Thanks ... . that was quick.  Just tried it  ... works great with https.  Good to go.
