### ISSUE TITLE
Install error on examples/nuxt3/nuxt3-directus-blog/ 

### ISSUE THREAD

**Issue by jalamanderman** [directus/examples#152]
Hello,

I copy this directory, run `npm install ` and then when I run `npm run dev` I get:

` WARN  Module nuxt-directus is disabled due to incompatibility issues:                                                                                                                                                              12:49:48
 - [nuxt] Nuxt version `^3.0.0 || ^2.16.0` is required but currently using `3.0.0-rc.3`
`

Can this please be looked at?

I found this repo following along from this guide  https://directus.io/guides/get-started-building-a-nuxt-3-blog-with-directus/ at the bottom there is a link to the example.

**Comment by azrikahar** [comment]
Might be this issue reported over in nuxt-directus: https://github.com/Intevel/nuxt-directus/issues/65, which was seems to be resolved by https://github.com/Intevel/nuxt-directus/commit/641a504416f6ea43f7ad6dc820d3810d524ef547 in nuxt-directus v3.0.1. I assume it's a versioning difference as it's compatibility was bumped to nuxt `3.0.0-rc.9` in the linked commit, but the current example is still using `nuxt. cc @Intevel just in case I'm misunderstanding anything here 😄

That being said, I'll proceed to update the dependencies of the nuxt 3 example in _this_ repo and close this for now. Do try to ensure you see nuxt `3.0.0-rc.9` in your package.json after pulling the latest changes

**Comment by Intevel** [comment]
Yes, that was fixed. But now you have to upgrade to `nuxt@^3.0.0-rc.9` @jalamanderman
