### ISSUE TITLE
Astro example is broken

### ISSUE THREAD

**Issue by kgrady13** [directus/examples#176]
UPDATE: CLOSE ISSUE
It was a silly config problem by me the whole time. My apologies!

The following error shows:

```
const { location, pluginName, text } = e.errors[0];

TypeError: Cannot destructure property 'location' of 'e.errors[0]' as it is undefined.
    at collectErrorMetadata (/examples/astro/node_modules/astro/dist/core/errors.js:111:13)
    at handleRequest (/examples/astro/node_modules/astro/dist/vite-plugin-astro-server/index.js:229:31)
```

I have played around but anytime I try to bring in directus and call the API using the SDK the app explodes.

**Comment by azrikahar** [comment]
> UPDATE: CLOSE ISSUE
It was a silly config problem by me the whole time. My apologies!

No worries, glad it's resolved!
