### ISSUE TITLE
Docker directus example and git workflow database

### ISSUE THREAD

**Issue by yohannTum** [directus/examples#181]
Hello,

I am looking for a way to make my directus available on github as a public repos. Just like in your directus folder, the directus database is in raw binary. I find it difficult to do a versioning on a binary file. I found in your documentation about how to dockerise your app, but about dumping the database, I am not sure what to do.

Is it possible to make a PR named directus-docker for example and give an example of a workflow with exporting/importing the dump database so that it is easier to keep track of the versioning of my dataset with git? Would it be usefull for someone?

**Comment by rijkvanzanten** [comment]
Heya! It isn't very common to store full database contents in version control (like git), so we don't offer an officially recommended way to do that. You could rely on [custom migration scripts](https://docs.directus.io/extensions/migrations.html), the [schema migration snapshots](https://docs.directus.io/self-hosted/cli.html#migrate-schema-to-a-different-environment) (for data model), or any other means of exporting/importing data from the DB directly (f.e. as json/csv/sql files)
