### ISSUE TITLE
Cors Error

### ISSUE THREAD

**Issue by bastianhilton** [directus/examples#187]
Hello i'm receiving a cors error when attempting to connect using the Nuxt-Directus module yet in the examples there is no cors option, what am I missing?

This is my nuxt.config section with directus:

```
directus: {
    url: process.env.DIRECTUS_URL,
    auth: {
      email: process.env.DIRECTUS_EMAIL,
      password: process.env.DIRECTUS_PASSWORD,
      token: process.env.DIRECTUS_TOKEN,
    }
  },
```

**Comment by paescuj** [comment]
If you're using the example setup from this repo this has now been addressed in #190. See also the documentation: https://docs.directus.io/self-hosted/config-options.html#cors
