### ISSUE TITLE
Astro Example: You don't have permission to access this.

### ISSUE THREAD

**Issue by ChristophWolfPCG** [directus/examples#188]
![image](https://user-images.githubusercontent.com/129749463/231752246-4b7a7275-e49a-46f1-9fbb-fc8c565f6393.png)

docker image is running,
static token is provided (same error even without)
login data is correct

**Comment by ChristophWolfPCG** [comment]
had the wrong directus image pulled that was supposed to be prepopulated with articles, obviously when you look at the code in the astro project, but you know how it is, initially everything is gibberish... or gibberish for the sake of security... you definitely need those dev, prev, prod error modes...

**Comment by MarvinXu** [comment]
I got the same error even without stacktrace... The error message makes no sense. Glad you made this issue, or I won't have solved this.
