### ISSUE TITLE
Vue example doesn't work - docker-compose file is invalid

### ISSUE THREAD

**Issue by phlummox** [directus/examples#192]
On Ubuntu at least, it appears pull request #190 does not, in fact, fix CORS issues, but rather breaks the docker-compose file.

## Version used

- this repository: commit afd391c
- directus: 9.22.1
- docker-compose: version 1.24.0 (build 0aa59064), also tested with version 1.25.0 (installed using `apt-get`, build unknown)

## Steps to reproduce (on Ubuntu 22.04)

- Clone the repo

  `git clone https://github.com/directus/examples`

- In a terminal, `cd` into `directus` within the repo, and `docker-compose up`

## Expected behaviour

The containers specified in the docker-compose.yml file should be started.

## Actual behaviour

Docker-compose fails with an error:

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.directus.environment.CORS_ENABLED contains true, which is an invalid type, it should be a string, number, or a null
```

## Comments

The same error also occurs on Fedora 38, running docker-compose version 1.29.2. I'm curious as to how pull requests to this repository are being tested before they're merged. If no testing of pull requests is being done, perhaps that's something you could incorporate into your processes.

It might also be a good idea to test that bugs are fixed before they are closed, since even a very cursory attempt to reproduce bug #189 would likely have revealed the bug being reported in this issue.

I realise the examples in this repo aren't intended to be "production ready", but still, closing bugs as fixed when they are not doesn't seem like best practice.

**Comment by paescuj** [comment]
Back then it has been tested and still works with Compose V2 (see https://docs.docker.com/compose/migrate/).
Nevertheless, it should now also work with the old `docker-compose` command after https://github.com/directus/examples/commit/b3229b253914a14a916cb8701fd048a03ec0bf5b.
