### ISSUE TITLE
Vue example not displaying content

### ISSUE THREAD

**Issue by jjaimealeman** [directus/examples#56]
Fresh installation based on the Examples directions.

I tested the Astro example, works fine.
However, the Vue example, does not. The `.env.example` copied as `.env`.

I closed the Directus server and the Vue/Vite server - and relaunched. 

http://localhost:8055/ comes up fine.

http://localhost:3000/ just does not display any articles.

![screenshot](https://i.imgur.com/03MW9an.png)

**Comment by jjaimealeman** [comment]
BTW: just tested the NuxtJS example version, and it works beautifully.

**Comment by rijkvanzanten** [comment]
I haven't tested it locally (yet), but from the codebase it should set the base url for directus to 8055 here:

https://github.com/directus/examples/blob/4c3f0c3a3dc606fbf309fd00f96b7ba792855261/vue/src/services/directus.js#L3

pulled in from the `.env` here:

https://github.com/directus/examples/blob/4c3f0c3a3dc606fbf309fd00f96b7ba792855261/vue/.env.example#L1

**Comment by rijkvanzanten** [comment]
@jjaimealeman This seems to work as expected on my end! Did you change the value in `.env` by any chance?

Steps I took (with the demo Directus instance running):

```
cd vue
npm install
cp .env.example .env
npm run dev
```

(That reminds me @azrikahar, we could drop the requirement on the `.env` files in favor of just hardcoding the example `localhost:8080`, but i'll leave that up to you 👍🏻 )

**Comment by rijkvanzanten** [comment]
I'll close this for now, as I believe this works as expected. Lemme know if I'm missing anything @jjaimealeman 🙂

**Comment by azrikahar** [comment]
> This seems to work as expected on my end! 

Works on my end as well! I believe it is indeed `VITE_DIRECTUS_URL` not loading (somehow) for OP since it's showing `:3000` in the screenshot instead.

> we could drop the requirement on the `.env` files in favor of just hardcoding the example 

That's true! Actually it initially stemmed from we weren't providing the local directus instance so it _may_ not be `localhost:8055`, hence the attempt at making it easier to configure via `.env` files. 😄

**Comment by rijkvanzanten** [comment]
> That's true! Actually it initially stemmed from we weren't providing the local directus instance so it may not be localhost:8055, hence the attempt at making it easier to configure via .env files. 

Ahh good one, yeah!
